LAP/innovation4austria.web/innovation4austria.web/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using innovation4austria.dataAccess;
using innovation4austria.logic;
using innovation4austria.web;
using innovation4austria.web.Models;
using System.Xml.Linq;
using innovation4austria.web.AppCode;

namespace innovation4austria.web.Controllers
{
    public class RoomController : Controller
    {
        // GET: Room
        public ActionResult Index()
        {
            RoomFilterModel rfm = new RoomFilterModel();
            rfm.Filter = new FilterModel();
            rfm.Rooms = new List<RoomModel>();

            List<rooms> allRooms = RoomAdministration.GetRooms();
            List<RoomModel> model = new List<RoomModel>();

            rfm.Filter.Furnishings = new List<FilterFurnishingModel>();
            List<furnishings> allFurnishings = new List<furnishings>();
            allFurnishings = RoomAdministration.GetFurnishings();

            FilterModel fm = new FilterModel();
            fm.Furnishings = new List<FilterFurnishingModel>();

            if (Session[User.Identity.Name] != null)
            {
                fm = (FilterModel)Session[User.Identity.Name];
            }
            else
            {
                foreach (var f in allFurnishings)
                {
                    fm.Furnishings.Add(new FilterFurnishingModel() { Description = f.description, Id = f.id });
                }
                fm.StartDate = DateTime.Now;
                fm.EndDate = DateTime.Now;
            }


            List<rooms> filteredRooms = new List<rooms>();

            if (Session[User.Identity.Name] != null)
            {

                List<rooms> allrooms = RoomAdministration.GetRooms(fm.StartDate, fm.EndDate);

                // Filterlogik aufrufen
                if (fm.Price > 0)
                {
                    allRooms = allRooms.Where(x => x.price <= fm.Price).ToList();
                }

                /// ermittle alle Räume
                /// die zwischen fm.StartDate und fm.EndDate NICHT gebucht sind
                


                //if (fm.StartDate > DateTime.Now)
                //{
                //    // Testen!!
                //    allRooms = allRooms.Where(x => x.bookings.Any(y => y.startdate <= fm.StartDate)).ToList();
                //}
                //if (fm.EndDate > fm.StartDate || fm.EndDate > DateTime.Now)
                //{


                //    allRooms = allRooms.Where(x => x.bookings.Any(y => y.enddate <= fm.EndDate)).ToList();


                //}


                if (!string.IsNullOrEmpty(fm.Facility))
                {
                    allRooms = allRooms.Where(x => x.facilities.facilityname == fm.Facility).ToList();
                }
                if (fm.Furnishings != null && fm.Furnishings.Count > 0)
                {
                    // Testen!!
                    //allRooms = allRooms.Where(x => x.roomfurnishings.Any(y => fm.Furnishings.Exists(z => z.Id == y.furnishing_id))).ToList();
                     allRooms = allRooms.Where(x => fm.Furnishings.All(y => x.roomfurnishings.Any(z => z.furnishing_id == y.Id))).ToList();
                }
                //else if (fm.Furnishings  == null || fm.Furnishings.Count == 0)
                //{
                //    List<furnishings> dbFurnishings = new List<furnishings>();
                //    dbFurnishings = RoomAdministration.GetFurnishings();

                //    foreach (var f in dbFurnishings)
                //    {
                //        fm.Furnishings.Add(new FilterFurnishingModel() { Description = f.description, Id = f.id });
                //    }
                //}
            }

            if (User.IsInRole("admin"))
            {


                foreach (var room in allRooms)
                {
                    RoomModel rm = new RoomModel();
                    rm.Description = room.description;
                    rm.Facility_ID = room.facility_id;
                    rm.Facility_Name = room.facilities.facilityname;
                    rm.Furnishings = new List<FurnishingModel>();
                    rm.ID = room.id;
                    rm.Price = room.price;

                    List<furnishings> dbFurnishings = new List<furnishings>();
                    dbFurnishings = RoomAdministration.GetFurnishingsByRoomId(room.id);

                    foreach (var f in dbFurnishings)
                    {
                        FurnishingModel furModel = new FurnishingModel();
                        furModel.Description = f.description;
                        furModel.ID = f.id;
                        furModel.Room_ID = room.id;
                        rm.Furnishings.Add(furModel);
                    }

                    model.Add(rm);
                }


            }
            else if (User.Identity.IsAuthenticated)
            {


                foreach (var room in allRooms)
                {
                    RoomModel rm = new RoomModel();
                    rm.Description = room.description;
                    rm.Facility_ID = room.facility_id;
                    rm.Facility_Name = room.facilities.facilityname;
                    rm.Furnishings = new List<FurnishingModel>();
                    rm.ID = room.id;
                    rm.Price = room.price;

                    List<furnishings> dbFurnishings = new List<furnishings>();
                    dbFurnishings = RoomAdministration.GetFurnishingsByRoomId(room.id);

                    foreach (var f in dbFurnishings)
                    {
                        FurnishingModel furModel = new FurnishingModel();
                        furModel.Description = f.description;
                        furModel.ID = f.id;
                        furModel.Room_ID = room.id;
                        rm.Furnishings.Add(furModel);
                    }

                    model.Add(rm);
                }
            }
            rfm.Rooms = model;
            rfm.Filter = fm;
            return View(rfm);
        }

        public ActionResult Reset()
        {
            Session[User.Identity.Name] = null;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Filter(DateTime startdate, DateTime enddate, string facility, List<int> furnishingId, decimal price)
        {
            //neues FilterModel mit Werten vom Formular befüllen
            FilterModel fm = new FilterModel();
            fm.Furnishings = new List<FilterFurnishingModel>();
            if (facility != null)
            {
                fm.Facility = facility;
            }
            if (furnishingId != null)
            {
                // Befüllen der Furnishings
                List<furnishings> dbFurnishings = new List<furnishings>();
                dbFurnishings = RoomAdministration.GetFurnishings();

                foreach (var f in dbFurnishings)
                {
                    foreach (var id in furnishingId)
                    {
                        if (f.id == id)
                        {
                            fm.Furnishings.Add(new FilterFurnishingModel() { Id = f.id, Description = f.description });
                        }
                    }
                }
            }
         

            fm.StartDate = startdate;
            fm.EndDate = enddate;
            fm.Price = price;

            Session[User.Identity.Name] = fm;
            return RedirectToAction("index");
        }

        [HttpGet]
        public ActionResult RoomDetail(int id)
        {
            List<furnishings> allFurnishings = RoomAdministration.GetFurnishingsByRoomId(id);
            List<FurnishingModel> model = new List<FurnishingModel>();

            if (User.IsInRole("admin"))
            {
                foreach (var furnishing in allFurnishings)
                {
                    model.Add(new FurnishingModel() { Description = furnishing.description, ID = furnishing.id, Room_ID = id });
                }
            }
            else if (User.Identity.IsAuthenticated)
            {
                foreach (var furnishing in allFurnishings)
                {

                    model.Add(new FurnishingModel() { Description = furnishing.description, ID = furnishing.id, Room_ID = id });

                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult CreateRoom(int id)
        {

            CreateRoomModel model = new CreateRoomModel()
            {
                ID = id
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRoom(CreateRoomModel model)
        {
            ActionResult result = View(model);

            if (ModelState.IsValid)
            {
                if (RoomAdministration.CreateRoom(model.Facility_ID, model.Description, model.Price))
                {
                    TempData[Constants.Messages.SUCCESS] = Constants.Messages.SaveSuccess;
                    result = RedirectToAction("Index", new { id = model.ID });
                }
                else
                {
                    TempData[Constants.Messages.ERROR] = Constants.Messages.SaveError;

                }
            }
            else
            {
                TempData[Constants.Messages.WARNING] = Constants.Messages.CreateEmployeInvalid;
            }

            return result;
        }
        [HttpGet]
        public ActionResult CreateFurnishing(int id)
        {

            CreateFurnishingModel model = new CreateFurnishingModel()
            {
                Room_ID = id
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFurnishing(CreateFurnishingModel model)
        {
            ActionResult result = View(model);

            if (ModelState.IsValid)
            {

LAP/innovation4austria.web/innovation4austria.web/Views/Room/CreateFurnishing.cshtml
@model innovation4austria.web.Models.CreateFurnishingModel

@{
    ViewBag.Title = "CreateFurnishing";
}
<div class="container">
    <h2>CreateFurnishing</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Room_ID)
        <div class="form-horizontal">
            <h4>CreateFurnishingModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="row">
                <div class="col-md-2">
                    @Html.LabelFor(x => x.Room_ID)
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.Room_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                </div>
            </div>*@
            <div class="row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Zurück", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
}

LAP/innovation4austria.web/innovation4austria.web/Views/Room/CreateRoom.cshtml
@model innovation4austria.web.Models.CreateRoomModel

@{
    ViewBag.Title = "CreateRoom";
}
<div class="container">
    <h2>CreateRoom</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CreateRoomModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Facility_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Facility_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Facility_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

LAP/innovation4austria.web/innovation4austria.web/Views/Room/Index.cshtml
@model innovation4austria.web.Models.RoomFilterModel

@{
    ViewBag.Title = "Index";
}



@if (User.IsInRole("admin"))
{
    <div class="container">

        <div>
            Filter
            <br />
            @using (Html.BeginForm("Filter", "Room", new AjaxOptions() { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result" }))
            {
                @Html.Label("Start Datum")
                @*@Html.TextBoxFor(x => x.Filter.StartDate)*@
                <input type="text" name="startdate" value="@Model.Filter.StartDate.ToShortDateString()" />

                @Html.Label("End Datum")
                @*@Html.TextBoxFor(x => x.Filter.EndDate)*@
                <input type="text" name="enddate" value="@Model.Filter.EndDate.ToShortDateString()" />

                @Html.Label("Gebäude")
                @*@Html.TextBoxFor(x => x.Filter.Facility)*@
                <input type="text" name="facility" value="@Model.Filter.Facility" />

                @*@Html.ListBoxFor(x => x.Filter.Furnishings, new SelectList(Model.Filter.Furnishings, "Id", "Description"), new { @name = "Furnishings" })*@

            {
                SelectList sl = new SelectList(Model.Filter.Furnishings, "Id", "Description");

                @Html.ListBox("furnishingId", sl)
            }

            @Html.Label("Preis")
                @*@Html.TextBoxFor(x => x.Filter.Price)*@
                <input type="text" name="price" value="@Model.Filter.Price" />

                <br />
                @*<div class="row">
                    <div class="col-xs-12 text-center">*@
                <input type="submit" class="btn btn-primary btn-lg" value="Filtern" />
                <a href="@Url.Action("Reset", "Room")" class="btn btn-primary btn-lg">Filter zurücksetzen</a>
                @*</div>
                    </div>*@
            }


        </div>

        <h2>Alle Räume</h2>
        <table class="table" id="result">
            <tr>
                <th>
                    <label>Geb&auml;ude</label>
                </th>
                <th>
                    <label>Beschreibung</label>
                </th>
                <th>
                    <label>Preis</label>
                </th>
                <th>
                    <label>Ausstattung</label>
                </th>
            </tr>

                        @foreach (var item in Model.Rooms)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Facility_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @foreach (var f in item.Furnishings)
                    {
                                        @Html.DisplayFor(modelItem => f.Description)
                                    }
                                </td>

                                <td>
                                    @using (Html.BeginForm("Room", "Booking", FormMethod.Get))
                                    {
                                        <input type="hidden" value="@item.ID" name="id" />
                                        <input type="hidden" value="@Model.Filter.StartDate" name="startdate" />
                                        <input type="hidden" value="@Model.Filter.EndDate" name="enddate" />

                                        <input type="submit" value="Buchen" />
                                    }
                                </td>
                                <td>
                                    @Html.ActionLink("Neuen Raum erstellen", "createroom", new { id = item.ID })|
                                    @Html.ActionLink("Details", "roomdetail", new { id = item.ID })|
                                    @Html.ActionLink("Löschen", "Delete", new { id = item.ID })
                                </td>
                            </tr>
           
            }

        </table>
    </div>
}
else
{
<div class="container">

    <div>
        Filter
        <br />
        @using (Html.BeginForm("Filter", "Room", new AjaxOptions() { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result" }))
            {
            @Html.Label("Start Datum")
            @*@Html.TextBoxFor(x => x.Filter.StartDate)*@
            <input type="text" name="startdate" value="@Model.Filter.StartDate.ToShortDateString()" />

                @Html.Label("End Datum")
                @*@Html.TextBoxFor(x => x.Filter.EndDate)*@
                <input type="text" name="enddate" value="@Model.Filter.EndDate.ToShortDateString()" />

                @Html.Label("Gebäude")
                @*@Html.TextBoxFor(x => x.Filter.Facility)*@
                <input type="text" name="facility" value="@Model.Filter.Facility" />

                @*@Html.ListBoxFor(x => x.Filter.Furnishings, new SelectList(Model.Filter.Furnishings, "Id", "Description"), new { @name = "Furnishings" })*@

        {
            SelectList sl = new SelectList(Model.Filter.Furnishings, "Id", "Description");

            @Html.ListBox("furnishingId", sl)
        }

        @Html.Label("Preis")
            @*@Html.TextBoxFor(x => x.Filter.Price)*@
            <input type="text" name="price" value="@Model.Filter.Price" />

                <br />
                @*<div class="row">
                    <div class="col-xs-12 text-center">*@
                <input type="submit" class="btn btn-primary btn-lg" value="Filtern" />
                <a href="@Url.Action("Reset", "Room")" class="btn btn-primary btn-lg">Filter zurücksetzen</a>
                @*</div>
                    </div>*@
        }


    </div>

    <h2>Alle Räume</h2>
    <table class="table" id="result">
        <tr>
            <th>
                <label>Geb&auml;ude</label>
            </th>
            <th>
                <label>Beschreibung</label>
            </th>
            <th>
                <label>Preis</label>
            </th>
            <th>
                <label>Ausstattung</label>
            </th>
        </tr>

        @foreach (var item in Model.Rooms)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Facility_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @foreach (var f in item.Furnishings)
                    {
                        @Html.DisplayFor(modelItem => f.Description)
                    }
                </td>
                <td>
                    @using (Html.BeginForm("Room", "Booking", FormMethod.Get))
                    {
                        <input type="hidden" value="@item.ID" name="id" />
                            <input type="hidden" value="@Model.Filter.StartDate" name="startdate" />
                            <input type="hidden" value="@Model.Filter.EndDate" name="enddate" />

                            <input type="submit" value="Buchen" />
                    }
                </td>
            </tr>
        }

    </table>
</div>
}

LAP/innovation4austria.web/innovation4austria.web/Views/Room/RoomDetail.cshtml
@model IEnumerable<innovation4austria.web.Models.FurnishingModel>

@{
    ViewBag.Title = "RoomDetail";
}
<div class="container">
    <h2>RoomDetail</h2>

    @if (User.IsInRole("admin"))
    {
        foreach (var furnishing in Model)
        {
            <div class="row">
                <div class="col-md-2 hidden-xs hidden-sm">
                    @furnishing.Description
                </div>
                <div class="col-md-2 col-sm-4">
                    <a href="@Url.Action("CreateFurnishing", "Room", new { id =  furnishing.Room_ID })">Erstellen</a>
                </div>
            </div>

        }
    }
    else
    {
        foreach (var furnishing in Model)
        {
            <div class="row">
                <div class="col-md-2 hidden-xs hidden-sm">
                    @furnishing.Description
                </div>
            </div>

        }
    }

    <p>
        @Html.ActionLink("Zurück", "Index")
    </p>
</div>