LAP/innovation4austria.web/innovation4austria.web/Controllers/BillController.cs
using innovation4austria.dataAccess;
using innovation4austria.logic;
using innovation4austria.web.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace innovation4austria.web.Controllers
{
    public class BillController : Controller
    {
        // GET: Bill
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CompanyBills()
        {
            int company_id = UserAdministration.GetCompanyIdFromUser(User.Identity.Name);

            List<bills> allBills = BillAdministration.GetBills();
            List<BillModel> model = new List<BillModel>();

            foreach (var bill in allBills)
            {
                model.Add(new BillModel()
                {
                    ID = bill.id,
                    Date = bill.date,
                    Company_ID = bill.company_id
                });
            }

            return new ViewAsPdf(model);
        }

        //[HttpGet]
        //public ActionResult Create()
        //{
        //    List<CreateBillModel> model = new List<CreateBillModel>();
        //    for (DateTime date = new DateTime(DateTime.Now.Year - 1, 1, 1); date <= DateTime.Now.AddMonths(1); date = date.AddMonths(1))
        //    {
        //        model.Add(new CreateBillModel()
        //        {
        //            Year = date.Year,
        //            Month = (date.Month),
        //            IsPaid = BillAdministration.BookingExist(date.Month, date.Year),
        //            BookingExist = BillAdministration.BookingExistsInTimePeriod(date.Month, date.Year),
        //            SoonestBillDate = new DateTime(date.Year, date.Month, 1).AddMonths(1)
        //        });
        //    }
        //    return View(model);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(int month, int year)
        //{
        //    bool success = BillAdministration.CreateBills(month, year);

        //    return RedirectToAction("CreateCompanyBills");
        //}



        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult GeneratePDF(int id)
        {
            // Erstelle PDF für die Rechnung

            bills pdfBill = new bills();
            pdfBill = BillAdministration.GetBillById(id);

            List<bookingdetails> bdList = new List<bookingdetails>();
            bdList = pdfBill.bookingdetails.ToList();

            List<rooms> rList = new List<rooms>();
            rList = RoomAdministration.GetRooms();

            List<bookings> bList = new List<bookings>();
            bList = BookingAdministration.GetBookings();

            PdfModel model = new PdfModel();
            model.Billdate = pdfBill.date;
            model.Id = pdfBill.id;

            decimal totalPrice = 0;

            model.Bookingdetails = new List<BookingDetailModel>();

            foreach (var item in bdList)
            {
                model.Bookingdetails.Add(new BookingDetailModel()
                {
                    ID = item.id,
                    Date = item.date,
                    Price = item.price,
                    Room = (from bd in bdList
                            join b in bList on bd.booking_id equals b.id
                            join r in rList on b.room_id equals r.id
                            where bd.id == item.id
                            select r.description).FirstOrDefault()
                });
                totalPrice += item.price;
            }
        
        model.Price = totalPrice;

            ViewAsPdf viewPdf = new ViewAsPdf("GeneratePDF", model);

                return View("GeneratePDF", model);
    }


        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionAsPdf Download(int id)
        {
            return new ActionAsPdf("GeneratePDF", new { id });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            // Hier wird die Logik aufgerufen, um die Rechnungen für das vergangene Monat für alle Firmen zu erzeugen
            bool success = BillAdministration.CreateBills();

            if (success)
            {
                TempData[AppCode.Constants.Messages.BillSuccess] = "Rechnungen erfolgreich erstellt!";
                return RedirectToAction("Index", "Home");
            }

            TempData[AppCode.Constants.Messages.ERROR] = "Es ist ein Fehler passiert!";
            return RedirectToAction("Index", "Home");
        }
    }
}

LAP/innovation4austria.web/innovation4austria.web/Views/Bill/CompanyBills.cshtml
@{
    ViewBag.Title = "CompanyBills";
}

<h2>CompanyBills</h2>

LAP/innovation4austria.web/innovation4austria.web/Views/Bill/Create.cshtml
@model IEnumerable<innovation4austria.web.Models.CreateBillModel>

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<div class="container">
    <table>
        <tr>
            <th>Jahr</th>
            <th>Monat</th>
            <th>Status</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Year
                </td>
                <td>
                    @item.Month
                </td>
                <td>
                    @if (item.IsPaid)
                {
                        <p><i>Bereits bezahlt</i></p>
                    }
                    else if (!item.BookingExist)
                    {
                        <span><i>Keine Buchungen vorhanden</i></span>
                    }
                    else if (item.SoonestBillDate > DateTime.Now)
                    {
                        <span>Kann erst nächstes Monat abgerechnet werden!</span>
                    }
                    else
                    {
                        using (Html.BeginForm("Create", "Bill"))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("month", item.Month, new { name = "month" })
                            @Html.Hidden("year", item.Year, new { name = "year" })
                            @*<input type="submit" class="btn btn-default" value="Rechnungen erzeugen" />*@

                        }

                    }
                </td>
            </tr>

        }
    </table>
        <input type="submit" class="btn btn-default" value="Rechnungen jetzt erzeugen" />

</div>

LAP/innovation4austria.web/innovation4austria.web/Views/Bill/GeneratePDF.cshtml
@model innovation4austria.web.Models.PdfModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <link rel="stylesheet" href="~/Content/BillDetail.css" />
</head>
<body>
    <header>
        <address>
            <p>innovations4austria GmbH</p>
            <p>1030 Wien,<br />Simmeringer Hauptstra&szlig;e 47</p>
            <p>(0043)1 321 456789</p>
        </address>
        <span><img alt="Signet" src="~/Content/img/favicon-96x96.png" /></span>
    </header>
    <article>
        <table class="meta">
            <tr>
                <th>PostenNr.:</th>
                <td>@Model.Id</td>
            </tr>
            <tr>
                <th>Datum:</th>
                <td>@Model.Billdate.ToShortDateString()</td>
            </tr>
        </table>
        <table class="inventory">
            <thead>
                <tr>
                    <th>Raum</th>
                    <th>Datum</th>
                    <th>Preis</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Bookingdetails)
                {
                    <tr>
                        <td>@item.Room</td>
                        <td>@item.Date.ToShortDateString()</td>
                        <td>&euro; @item.Price</td>
                    </tr>
                }
            </tbody>
        </table>
        <table class="balance">
            <tr>
                <th>Gesamtpreis</th>
                <td>&euro; @Model.Price</td>
            </tr>
        </table>
    </article>
</body>
</html>